name: Tomcat-deploy
# Controls when the workflow will run
on: [push]
  # Triggers the workflow on push or pull request events but only for the master branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Generate the package
        run: mvn -B package --file pom.xml
      - name: Ansible
        run: ansible --version
      #- name: Deploy to tomcat
       # run: curl -v -u ${{ secrets.TOMCAT_USER }}:${{ secrets.TOMCAT_PASSWORD }} -T /home/ubuntu/actions-runner/_work/java-project-github-actions/java-project-github-actions/target/WebApp-pipeline.war 'http://13.233.87.180:8080//manager/text/deploy?path=/web_app&update=true'
